=== jentlestea1/obs_xslt/obs/doc/xsd/metamodel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Vaclav Cechticky (Automatic Control Laboratory ETH Zuerich) -->
<!-- edited by Vaclav Cechticky (Automatic Control Laboratory ETH Zuerich) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <!-- new simple types -->
    <!-- the simple type "zero2inf" accepts data like 0, ..., 9999999...etc., and +, * -->
    <xs:simpleType name="zero2inf">
        <xs:restriction base="xs:token">
            <xs:pattern value="([1-9][0-9]*|0|\+|\*)"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="one2inf">
        <xs:restriction base="xs:token">
            <xs:pattern value="([1-9][0-9]*|\+|\*)"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="greaterThanZero">
        <xs:restriction base="xs:token">
            <xs:pattern value="([1-9][0-9]*)"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- definition of simple elements -->
    <!-- definition of attributes -->
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="type" type="xs:string"/>
    <xs:attribute name="nameOfFeature" type="xs:string"/>
    <xs:attribute name="nameOfGroup" type="xs:string"/>
    <xs:attribute name="nameOfMacro" type="xs:string"/>
    <xs:attribute name="nameOfCalledMacro" type="xs:string"/>
    <xs:attribute name="nameOfClass" type="xs:string"/>
    <xs:attribute name="macroName" type="xs:string"/>
    <xs:attribute name="appendedGroupName" type="xs:string"/>
    <xs:attribute name="appendedFeatureName" type="xs:string"/>
    <xs:attribute name="FeatureCardMin" type="greaterThanZero"/>
    <xs:attribute name="FeatureCardMax" type="one2inf"/>
    <xs:attribute name="GroupCardMin" type="zero2inf"/>
    <xs:attribute name="GroupCardMax" type="greaterThanZero"/>
    <xs:attribute name="newMinCard" type="zero2inf"/>
    <xs:attribute name="newMaxCard" type="zero2inf"/>
    <xs:attribute name="minValue" type="xs:string"/>
    <xs:attribute name="maxValue" type="xs:string"/>
    <xs:attribute name="value" type="xs:string"/>
    <xs:attribute name="text" type="xs:string"/>
    <xs:attribute name="classId" type="xs:string"/>
    <xs:attribute name="index" type="xs:integer"/>
    <xs:attribute name="status">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="missing"/>
                <xs:enumeration value="provided"/>
                <xs:enumeration value="generable"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <!-- definition of complex elements -->
    <xs:element name="FrameworkFeatureModel" type="FrameworkFeatureModelType">
        <!--
        <xs:unique name="UniqueGroupName">
            <xs:selector xpath=".//Group"/>
            <xs:field xpath="@nameOfGroup"/>
        </xs:unique>

		<xs:keyref name="macroNameKeyRef" refer="macroNameKey">
			<xs:selector xpath=".//Feature/CallMacro"/>
			<xs:field xpath="@name"/>
		</xs:keyref>
		<xs:key name="macroNameKey">
			<xs:selector xpath=".//Macro"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<xs:unique name="UniqueName">
			<xs:selector xpath=".//Feature|.//Group|.//Macro"/>
			<xs:field xpath="@name"/>
		</xs:unique>				
		<xs:unique name="UniqueFeatureName">
			<xs:selector xpath=".//Feature"/>
			<xs:field xpath="@name"/>
		</xs:unique> -->
        <!--
		<xs:unique name="UniqueMacroName">
			<xs:selector xpath=".//Macro"/>
			<xs:field xpath="@name"/>
		</xs:unique>		
		-->
    </xs:element>
    <xs:complexType name="FrameworkFeatureModelType">
        <xs:sequence>
            <xs:element ref="Feature" minOccurs="0"/>
            <xs:element ref="Macro" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute ref="name" use="optional"/>
    </xs:complexType>
    <xs:element name="Feature">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Description" minOccurs="0"/>
                <xs:element ref="FeatureComment" minOccurs="0"/>
                <xs:element ref="FeatureCardinality"/>
                <xs:element ref="Type"/>
                <xs:element ref="Group" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="nameOfFeature" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="CallMacro">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="CallMacroComment" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute ref="nameOfCalledMacro" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Group">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Description" minOccurs="0"/>
                <xs:element ref="GroupComment" minOccurs="0"/>
                <xs:element ref="GroupCardinality"/>
                <xs:choice maxOccurs="unbounded">
                    <xs:element ref="Feature"/>
                    <xs:element ref="CallMacro"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute ref="nameOfGroup" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="FeatureCardinality">
        <xs:complexType>
            <xs:attribute ref="FeatureCardMin" use="required"/>
            <xs:attribute ref="FeatureCardMax" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="GroupCardinality">
        <xs:complexType>
            <xs:attribute ref="GroupCardMin" use="required"/>
            <xs:attribute ref="GroupCardMax" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Option">
        <xs:complexType>
            <xs:attribute ref="value" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Macro">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="Feature"/>
                <xs:element ref="Extension"/>
            </xs:choice>
            <xs:attribute ref="nameOfMacro" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Extension">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Description" minOccurs="0"/>
                <xs:choice maxOccurs="unbounded">
                    <xs:element ref="AppendFeatureToGroup"/>
                    <xs:element ref="AppendGroupToFeature"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute ref="macroName" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="AppendFeatureToGroup">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ModifyGroupCardinality" minOccurs="0"/>
                <xs:element ref="Feature" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="appendedGroupName" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="AppendGroupToFeature">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Group" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="appendedFeatureName" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ModifyGroupCardinality">
        <xs:complexType>
            <xs:attribute ref="newMinCard" use="required"/>
            <xs:attribute ref="newMaxCard" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Description">
        <xs:complexType>
            <xs:attribute ref="text" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="FeatureComment">
        <xs:complexType>
            <xs:attribute ref="text" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="GroupComment">
        <xs:complexType>
            <xs:attribute ref="text" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="CallMacroComment">
        <xs:complexType>
            <xs:attribute ref="text" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="BuildingBlock">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="Aspect"/>
                <xs:element ref="Component"/>
                <xs:element ref="Interface"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="Aspect">
        <xs:complexType>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
            <xs:attribute ref="type" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Attribute">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="Property"/>
                <xs:element ref="IndexedProperty"/>
                <xs:element ref="Operation"/>
                <xs:element ref="ObjectList"/>
                <xs:element ref="EventListener"/>
                <xs:element ref="Functionality"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="Component">
        <xs:complexType>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
            <xs:attribute ref="type" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Composite">
        <xs:complexType/>
    </xs:element>
    <xs:element name="Interface">
        <xs:complexType>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
            <xs:attribute ref="type" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Type">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="Attribute"/>
                <xs:element ref="BuildingBlock"/>
                <xs:element ref="Composite"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="Range">
        <xs:complexType>
            <xs:attribute ref="minValue" use="required"/>
            <xs:attribute ref="maxValue" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Enumeration">
        <xs:complexType/>
    </xs:element>
    <xs:element name="Property">
        <xs:complexType>
            <xs:choice minOccurs="0">
                <xs:element ref="Range"/>
                <xs:element name="Enumeration">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Item" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute ref="value" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
            <xs:attribute ref="type" use="required"/>
            <xs:attribute ref="value" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="IndexedProperty">
        <xs:complexType>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
            <xs:attribute ref="type" use="required"/>
            <xs:attribute ref="value" use="optional"/>
            <xs:attribute ref="index" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ObjectList">
        <xs:complexType>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
            <xs:attribute ref="type" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Operation">
        <xs:complexType>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="EventListener">
        <xs:complexType>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
            <xs:attribute ref="type" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Functionality">
        <xs:complexType>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jentlestea1/obs_xslt/obs/models/xml/FeatureParameterDatabase.xml
<?xml version="1.0" encoding="utf-8"?>
<FrameworkFeatureModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:/Projects/fbfm/fwmetamodel/xsd/metamodel.xsd">
      <Macro nameOfMacro="ParameterDatabase">
            <Feature nameOfFeature="ParameterDatabase">
                  <Description text="The parameter database "/>
                  <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                  <Type>
                        <BuildingBlock>
                              <Interface status="provided" type="Data/ParameterDatabase"/>
                        </BuildingBlock>
                  </Type>
                  <Group nameOfGroup="ParameterDatabaseOptions">
                        <Description text="The implementation options for the parameter database offered by the framework"/>
                        <GroupCardinality GroupCardMin="1" GroupCardMax="1"/>
                        <Feature nameOfFeature="Custom">
                              <Description text="An application-specific parameter database not provided by the framework"/>
                              <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                              <Type>
                                    <BuildingBlock>
                                          <Component status="missing"/>
                                    </BuildingBlock>
                              </Type>
                        </Feature>
                        <Feature nameOfFeature="BasicDatabase">
                              <Description text="A parameter database with basic functionalities and minimal overheads"/>
                              <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                              <Type>
                                    <BuildingBlock>
                                          <Component status="provided" type="Data/DC_BasicDatabase"/>
                                    </BuildingBlock>
                              </Type>
                              <Group nameOfGroup="BasicDatabaseAttributes">
                                    <Description text="The attributes of the basic database"/>
                                    <GroupCardinality GroupCardMin="4" GroupCardMax="4"/>
                                    <Feature nameOfFeature="DatabaseSize">
                                          <Description text="The size in bytes of the database"/>
                                          <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                                          <Type>
                                                <Attribute>
                                                      <Property status="provided" type="int" name="TableLength">
                                                            <Range minValue="1" maxValue="+"/>
                                                      </Property>
                                                </Attribute>
                                          </Type>
                                    </Feature>
                                    <Feature nameOfFeature="OperationalTable">
                                          <Description text="The starting address of the operational table"/>
                                          <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                                          <Type>
                                                <Attribute>
                                                      <Property status="provided" type="string" name="OperationalTable"/>
                                                </Attribute>
                                          </Type>
                                    </Feature>
                                    <Feature nameOfFeature="DefaultTable">
                                          <Description text="The starting address of the default table"/>
                                          <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                                          <Type>
                                                <Attribute>
                                                      <Property status="provided" type="string" name="DefaultTable"/>
                                                </Attribute>
                                          </Type>
                                    </Feature>
                                    <Feature nameOfFeature="DatabaseItem">
                                          <Description text="An item in the database"/>
                                          <FeatureCardinality FeatureCardMin="1" FeatureCardMax="+"/>
                                          <Type>
                                                <Composite/>
                                          </Type>
                                          <Group nameOfGroup="DatabaseItemAttributes">
                                                <Description text="The attributes of the database item"/>
                                                <GroupCardinality GroupCardMin="3" GroupCardMax="3"/>
                                                <Feature nameOfFeature="Id">
                                                      <Description text="The numerical identifier of the database parameter"/>
                                                      <FeatureComment text="Constraint: the id must be less than the database size"/>
                                                      <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                                                      <Type>
                                                            <Attribute>
                                                                  <Property status="provided" type="int">
                                                                        <Range minValue="0" maxValue="+"/>
                                                                  </Property>
                                                            </Attribute>
                                                      </Type>
                                                </Feature>
                                                <Feature nameOfFeature="Name">
                                                      <Description text="The name of the database parameter"/>
                                                      <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                                                      <Type>
                                                            <Attribute>
                                                                  <Property status="provided" type="string"/>
                                                            </Attribute>
                                                      </Type>
                                                </Feature>
                                                <Feature nameOfFeature="Type">
                                                      <Description text="The syntactical type of the database parameter"/>
                                                      <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                                                      <Type>
                                                            <Attribute>
                                                                  <Property status="provided" type="string">
                                                                        <Enumeration>
                                                                              <Item value="float"/>
                                                                              <Item value="double"/>
                                                                              <Item value="int"/>
                                                                              <Item value="unsigned int"/>
                                                                              <Item value="short"/>
                                                                              <Item value="unsigned short"/>
                                                                              <Item value="char"/>
                                                                              <Item value="unsigned char"/>
                                                                              <Item value="bool"/>
                                                                        </Enumeration>
                                                                  </Property>
                                                            </Attribute>
                                                      </Type>
                                                </Feature>
                                          </Group>
                                    </Feature>
                              </Group>
                        </Feature>
                        <CallMacro nameOfCalledMacro="IndexedDatabase"/>
                  </Group>
            </Feature>
      </Macro>
</FrameworkFeatureModel>

=== jentlestea1/obs_xslt/obs/models/xml/FeatureRecoveryActions.xml
<?xml version="1.0" encoding="utf-8"?>
<FrameworkFeatureModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="D:/Projects/fbfm/fwmetamodel/xsd/metamodel.xsd">
    <Macro nameOfMacro="RecoveryActions">
        <Feature nameOfFeature="RecoveryAction">
            <Description text="A recovery action"/>
            <FeatureCardinality FeatureCardMin="1" FeatureCardMax="+"/>
            <Type>
                <BuildingBlock><Interface status="provided" type="FDIR/RecoveryAction"/></BuildingBlock>
            </Type>
            <Group nameOfGroup="OptionalAttributes">
                <Description text="The optional attributes of the recovery action"/>
                <GroupCardinality GroupCardMin="0" GroupCardMax="1"/>
                <Feature nameOfFeature="InitialEnableStatus">
                    <Description text="The recovery action has a non-default initial enable status"/>
                    <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                    <Type>
                        <Attribute>
                            <Property status="provided" type="string" name="Enabled">
                                <Enumeration>
                                    <Item value="ENABLED"/>
                                    <Item value="DISABLED"/>
                                </Enumeration>
                            </Property>
                        </Attribute>
                    </Type>
                </Feature>
            </Group>
            <Group nameOfGroup="Options">
                <Description text="The recovery actions foreseen by the framework"/>
                <GroupCardinality GroupCardMin="1" GroupCardMax="1"/>
                <Feature nameOfFeature="Null">
                    <Description text="A null recovery action that does not do anything"/>
                    <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                    <Type>
                        <BuildingBlock><Component status="provided" type="FDIR/DC_NullRecoveryAction"/></BuildingBlock>
                    </Type>
                </Feature>
                <Feature nameOfFeature="Custom">
                    <Description text="An application-specific recovery action"/>
                    <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                    <Type>
                        <BuildingBlock><Component status="missing"/></BuildingBlock>
                    </Type>
                    <Group nameOfGroup="DefaultAttributes">
                        <Description text="The default attributes of a custom recovery actions"/>
                        <GroupCardinality GroupCardMin="0" GroupCardMax="1"/>
                        <CallMacro nameOfCalledMacro="DefaultAttributes"/>
                    </Group>
                </Feature>
            </Group>
        </Feature>
    </Macro>
</FrameworkFeatureModel>
