=== jentlestea1/obs_xslt/obs/doc/xsd/metamodel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Vaclav Cechticky (Automatic Control Laboratory ETH Zuerich) -->
<!-- edited by Vaclav Cechticky (Automatic Control Laboratory ETH Zuerich) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <!-- new simple types -->
    <!-- the simple type "zero2inf" accepts data like 0, ..., 9999999...etc., and +, * -->
    <xs:simpleType name="zero2inf">
        <xs:restriction base="xs:token">
            <xs:pattern value="([1-9][0-9]*|0|\+|\*)"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="one2inf">
        <xs:restriction base="xs:token">
            <xs:pattern value="([1-9][0-9]*|\+|\*)"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="greaterThanZero">
        <xs:restriction base="xs:token">
            <xs:pattern value="([1-9][0-9]*)"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- definition of simple elements -->
    <!-- definition of attributes -->
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="type" type="xs:string"/>
    <xs:attribute name="nameOfFeature" type="xs:string"/>
    <xs:attribute name="nameOfGroup" type="xs:string"/>
    <xs:attribute name="nameOfMacro" type="xs:string"/>
    <xs:attribute name="nameOfCalledMacro" type="xs:string"/>
    <xs:attribute name="nameOfClass" type="xs:string"/>
    <xs:attribute name="macroName" type="xs:string"/>
    <xs:attribute name="appendedGroupName" type="xs:string"/>
    <xs:attribute name="appendedFeatureName" type="xs:string"/>
    <xs:attribute name="FeatureCardMin" type="greaterThanZero"/>
    <xs:attribute name="FeatureCardMax" type="one2inf"/>
    <xs:attribute name="GroupCardMin" type="zero2inf"/>
    <xs:attribute name="GroupCardMax" type="greaterThanZero"/>
    <xs:attribute name="newMinCard" type="zero2inf"/>
    <xs:attribute name="newMaxCard" type="zero2inf"/>
    <xs:attribute name="minValue" type="xs:string"/>
    <xs:attribute name="maxValue" type="xs:string"/>
    <xs:attribute name="value" type="xs:string"/>
    <xs:attribute name="text" type="xs:string"/>
    <xs:attribute name="classId" type="xs:string"/>
    <xs:attribute name="index" type="xs:integer"/>
    <xs:attribute name="status">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="missing"/>
                <xs:enumeration value="provided"/>
                <xs:enumeration value="generable"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <!-- definition of complex elements -->
    <xs:element name="FrameworkFeatureModel" type="FrameworkFeatureModelType">
        <!--
        <xs:unique name="UniqueGroupName">
            <xs:selector xpath=".//Group"/>
            <xs:field xpath="@nameOfGroup"/>
        </xs:unique>

		<xs:keyref name="macroNameKeyRef" refer="macroNameKey">
			<xs:selector xpath=".//Feature/CallMacro"/>
			<xs:field xpath="@name"/>
		</xs:keyref>
		<xs:key name="macroNameKey">
			<xs:selector xpath=".//Macro"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<xs:unique name="UniqueName">
			<xs:selector xpath=".//Feature|.//Group|.//Macro"/>
			<xs:field xpath="@name"/>
		</xs:unique>				
		<xs:unique name="UniqueFeatureName">
			<xs:selector xpath=".//Feature"/>
			<xs:field xpath="@name"/>
		</xs:unique> -->
        <!--
		<xs:unique name="UniqueMacroName">
			<xs:selector xpath=".//Macro"/>
			<xs:field xpath="@name"/>
		</xs:unique>		
		-->
    </xs:element>
    <xs:complexType name="FrameworkFeatureModelType">
        <xs:sequence>
            <xs:element ref="Feature" minOccurs="0"/>
            <xs:element ref="Macro" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute ref="name" use="optional"/>
    </xs:complexType>
    <xs:element name="Feature">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Description" minOccurs="0"/>
                <xs:element ref="FeatureComment" minOccurs="0"/>
                <xs:element ref="FeatureCardinality"/>
                <xs:element ref="Type"/>
                <xs:element ref="Group" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="nameOfFeature" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="CallMacro">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="CallMacroComment" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute ref="nameOfCalledMacro" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Group">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Description" minOccurs="0"/>
                <xs:element ref="GroupComment" minOccurs="0"/>
                <xs:element ref="GroupCardinality"/>
                <xs:choice maxOccurs="unbounded">
                    <xs:element ref="Feature"/>
                    <xs:element ref="CallMacro"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute ref="nameOfGroup" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="FeatureCardinality">
        <xs:complexType>
            <xs:attribute ref="FeatureCardMin" use="required"/>
            <xs:attribute ref="FeatureCardMax" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="GroupCardinality">
        <xs:complexType>
            <xs:attribute ref="GroupCardMin" use="required"/>
            <xs:attribute ref="GroupCardMax" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Option">
        <xs:complexType>
            <xs:attribute ref="value" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Macro">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="Feature"/>
                <xs:element ref="Extension"/>
            </xs:choice>
            <xs:attribute ref="nameOfMacro" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Extension">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Description" minOccurs="0"/>
                <xs:choice maxOccurs="unbounded">
                    <xs:element ref="AppendFeatureToGroup"/>
                    <xs:element ref="AppendGroupToFeature"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute ref="macroName" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="AppendFeatureToGroup">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ModifyGroupCardinality" minOccurs="0"/>
                <xs:element ref="Feature" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="appendedGroupName" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="AppendGroupToFeature">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Group" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="appendedFeatureName" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ModifyGroupCardinality">
        <xs:complexType>
            <xs:attribute ref="newMinCard" use="required"/>
            <xs:attribute ref="newMaxCard" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Description">
        <xs:complexType>
            <xs:attribute ref="text" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="FeatureComment">
        <xs:complexType>
            <xs:attribute ref="text" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="GroupComment">
        <xs:complexType>
            <xs:attribute ref="text" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="CallMacroComment">
        <xs:complexType>
            <xs:attribute ref="text" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="BuildingBlock">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="Aspect"/>
                <xs:element ref="Component"/>
                <xs:element ref="Interface"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="Aspect">
        <xs:complexType>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
            <xs:attribute ref="type" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Attribute">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="Property"/>
                <xs:element ref="IndexedProperty"/>
                <xs:element ref="Operation"/>
                <xs:element ref="ObjectList"/>
                <xs:element ref="EventListener"/>
                <xs:element ref="Functionality"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="Component">
        <xs:complexType>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
            <xs:attribute ref="type" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Composite">
        <xs:complexType/>
    </xs:element>
    <xs:element name="Interface">
        <xs:complexType>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
            <xs:attribute ref="type" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Type">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="Attribute"/>
                <xs:element ref="BuildingBlock"/>
                <xs:element ref="Composite"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="Range">
        <xs:complexType>
            <xs:attribute ref="minValue" use="required"/>
            <xs:attribute ref="maxValue" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Enumeration">
        <xs:complexType/>
    </xs:element>
    <xs:element name="Property">
        <xs:complexType>
            <xs:choice minOccurs="0">
                <xs:element ref="Range"/>
                <xs:element name="Enumeration">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Item" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute ref="value" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
            <xs:attribute ref="type" use="required"/>
            <xs:attribute ref="value" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="IndexedProperty">
        <xs:complexType>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
            <xs:attribute ref="type" use="required"/>
            <xs:attribute ref="value" use="optional"/>
            <xs:attribute ref="index" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ObjectList">
        <xs:complexType>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
            <xs:attribute ref="type" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Operation">
        <xs:complexType>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="EventListener">
        <xs:complexType>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
            <xs:attribute ref="type" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Functionality">
        <xs:complexType>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="status" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jentlestea1/obs_xslt/obs/models/xml/FeatureDataItems.xml
<?xml version="1.0" encoding="utf-8"?>
<FrameworkFeatureModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:/Projects/fbfm/fwmetamodel/xsd/metamodel.xsd">
    <Macro nameOfMacro="DataItems">
        <Feature nameOfFeature="DataItem">
            <Description text="A data item"/>
            <FeatureCardinality FeatureCardMin="1" FeatureCardMax="+"/>
            <Type>
                <BuildingBlock>
                    <Interface status="provided" type="Data/DC_DataItem"/>
                </BuildingBlock>
            </Type>
            <Group nameOfGroup="Options">
                <Description text="The data item options foreseen by the framework"/>
                <GroupCardinality GroupCardMin="1" GroupCardMax="1"/>
                <Feature nameOfFeature="DefaultDataItem">
                    <Description text="Default data item"/>
                    <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                    <Type>
                        <BuildingBlock>
                            <Component status="provided" type="Data/DC_DataItem"/>
                        </BuildingBlock>
                    </Type>
                    <Group nameOfGroup="Attributes">
                        <GroupCardinality GroupCardMin="2" GroupCardMax="2"/>
                        <Feature nameOfFeature="Variable">
                            <Description text="The variable that is encapsulated by the data item"/>
                            <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                            <Type>
                                <Attribute>
                                    <Property status="provided" type="string"/>
                                </Attribute>
                            </Type>
                        </Feature>
                        <Feature nameOfFeature="Type">
                            <Description text="The type of the variable that is encapsulated by the data item"/>
                            <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                            <Type>
                                <Attribute>
                                    <Property status="provided" type="string">
                                        <Enumeration>
                                            <Item value="TD_Float"/>
                                            <Item value="TD_Integer"/>
                                        </Enumeration>
                                    </Property>
                                </Attribute>
                            </Type>
                        </Feature>
                    </Group>
                </Feature>
                <Feature nameOfFeature="RawDataItem">
                    <Description text="Raw data item"/>
                    <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                    <Type>
                        <BuildingBlock>
                            <Component status="provided" type="Data/DC_RawDataItem"/>
                        </BuildingBlock>
                    </Type>
                    <Group nameOfGroup="RawDataItemAttributes">
                        <GroupCardinality GroupCardMin="1" GroupCardMax="1"/>
                        <Feature nameOfFeature="Variable">
                            <Description text="The variable or the address that is encapsulated by the data item"/>
                            <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                            <Type>
                                <Attribute>
                                    <Property status="provided" type="string"/>
                                </Attribute>
                            </Type>
                        </Feature>
                    </Group>
                </Feature>
                <Feature nameOfFeature="SettableDataItem">
                    <Description text="Settable data item"/>
                    <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                    <Type>
                        <BuildingBlock>
                            <Component status="provided" type="Data/DC_SettableDataItem"/>
                        </BuildingBlock>
                    </Type>
                    <Group nameOfGroup="SettableDataItemAttributes">
                        <GroupCardinality GroupCardMin="2" GroupCardMax="2"/>
                        <Feature nameOfFeature="Variable">
                            <Description text="The variable that is encapsulated by the data item"/>
                            <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                            <Type>
                                <Attribute>
                                    <Property status="provided" type="string"/>
                                </Attribute>
                            </Type>
                        </Feature>
                        <Feature nameOfFeature="Type">
                            <Description text="The type of the variable that is encapsulated by the data item"/>
                            <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                            <Type>
                                <Attribute>
                                    <Property status="provided" type="string">
                                        <Enumeration>
                                            <Item value="TD_Float"/>
                                            <Item value="TD_Integer"/>
                                        </Enumeration>
                                    </Property>
                                </Attribute>
                            </Type>
                        </Feature>
                    </Group>
                </Feature>
            </Group>
        </Feature>
    </Macro>
</FrameworkFeatureModel>

=== jentlestea1/obs_xslt/obs/models/xml/FeatureFSM.xml
<?xml version="1.0" encoding="utf-8"?>
<FrameworkFeatureModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:/Projects/fbfm/fwmetamodel/xsd/metamodel.xsd">
    <Macro nameOfMacro="FSM">
        <Feature nameOfFeature="FSM">
            <Description text="A finite state machine"/>
            <FeatureCardinality FeatureCardMin="1" FeatureCardMax="*"/>
            <Type>
                <BuildingBlock>
                    <Component status="provided" type="FSM/CC_FSM"/>
                </BuildingBlock>
            </Type>
            <Group nameOfGroup="FSMOptionalAttributes">
                <Description text="The optional attributes of the FSM"/>
                <GroupCardinality GroupCardMin="0" GroupCardMax="1"/>
                <Feature nameOfFeature="InitialEnableStatus">
                    <Description text="The transition enable status has a non-default initial value"/>
                    <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                    <Type>
                        <Attribute>
                            <Property type="string" name="enabled" status="provided">
                                <Enumeration>
                                    <Item value="ENABLED"/>
                                    <Item value="DISABLED"/>
                                </Enumeration>
                            </Property>
                        </Attribute>
                    </Type>
                </Feature>
            </Group>
            <Group nameOfGroup="FsmStates">
                <Description text="The FsmStates associated to this FSM"/>
                <GroupCardinality GroupCardMin="1" GroupCardMax="1"/>
                <CallMacro nameOfCalledMacro="FsmStates"/>
            </Group>
            <Group nameOfGroup="FsmEvents">
                <Description text="The FsmEvents associated to this FSM"/>
                <GroupCardinality GroupCardMin="0" GroupCardMax="1"/>
                <CallMacro nameOfCalledMacro="FsmEvents"/>
            </Group>
        </Feature>
    </Macro>
</FrameworkFeatureModel>

=== jentlestea1/obs_xslt/obs/models/xml/FeaturePunctualActions.xml
<?xml version="1.0" encoding="utf-8"?>
<FrameworkFeatureModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/D:/Projects/fbfm/fwmetamodel/xsd/metamodel.xsd">
      <Macro nameOfMacro="PunctualActions">
            <Feature nameOfFeature="PunctualAction">
                  <Description text="A generic punctual action"/>
                  <FeatureComment text="More specific types of punctual actions (e.g. control actions) are defined in other parts of the feature model"/>
                  <FeatureCardinality FeatureCardMin="1" FeatureCardMax="+"/>
                  <Type>
                        <BuildingBlock>
                              <Interface status="provided" type="Base/PunctualAction"/>
                        </BuildingBlock>
                  </Type>
                  <Group nameOfGroup="OptionalAttributes">
                        <Description text="The optional attributes of the punctual action"/>
                        <GroupCardinality GroupCardMin="0" GroupCardMax="2"/>
                        <Feature nameOfFeature="PunctualActionInitialEnableStatus">
                              <Description text="The punctual action has a non-default initial enable status"/>
                              <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                              <Type>
                                    <Attribute>
                                          <Property status="provided" type="string" name="Enabled">
                                                <Enumeration>
                                                      <Item value="ENABLED"/>
                                                      <Item value="DISABLED"/>
                                                </Enumeration>
                                          </Property>
                                    </Attribute>
                              </Type>
                        </Feature>
                        <Feature nameOfFeature="ConditionalPunctualAction">
                              <Description text="The punctual action has an execution condition attached to it"/>
                              <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                              <Type>
                                    <Attribute>
                                          <Operation status="missing"/>
                                    </Attribute>
                              </Type>
                        </Feature>
                  </Group>
                  <Group nameOfGroup="Options">
                        <Description text="The generic punctual actions foreseen by the framework"/>
                        <GroupCardinality GroupCardMin="1" GroupCardMax="1"/>
                        <Feature nameOfFeature="CustomPunctualAction">
                              <Description text="An application-specific punctual action"/>
                              <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                              <Type>
                                    <BuildingBlock>
                                          <Component status="missing"/>
                                    </BuildingBlock>
                              </Type>
                              <Group nameOfGroup="DefaultAttributes">
                                    <Description text="The default attributes of a custom punctual action"/>
                                    <GroupCardinality GroupCardMin="0" GroupCardMax="1"/>
                                    <CallMacro nameOfCalledMacro="DefaultAttributes"/>
                              </Group>
                        </Feature>
                        <Feature nameOfFeature="DataPoolMonitor">
                              <Description text="A punctual action that performs profile monitoring on all data pool items"/>
                              <FeatureCardinality FeatureCardMin="1" FeatureCardMax="1"/>
                              <Type>
                                    <BuildingBlock>
                                          <Component status="provided" type="Data/DC_DataPoolMonitor"/>
                                    </BuildingBlock>
                              </Type>
                        </Feature>
                  </Group>
            </Feature>
      </Macro>
</FrameworkFeatureModel>
